spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**, /api/user/**
            - Method=GET,POST,PUT
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceBreaker
                fallbackUri: forward:/fallback/user
            - RewritePath=/fallback/(?<segment>.*), /$\{segment}
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**, /api/products/**
            - Method=GET,POST
          filters:
            - name: CircuitBreaker
              args:
                name: productServiceBreaker
                fallbackUri: forward:/fallback/product
            - RewritePath=/fallback/(?<segment>.*), /$\{segment}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**, /api/orders/**
            - Method=GET,POST
          filters:
            - name: CircuitBreaker
              args:
                name: orderServiceBreaker
                fallbackUri: forward:/fallback/order
            - RewritePath=/fallback/(?<segment>.*), /$\{segment}
    config:
      enabled: false

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      productServiceBreaker:
        baseConfig: default
      orderServiceBreaker:
        baseConfig: default
      userServiceBreaker:
        baseConfig: default

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics,loggers,env,circuitbreakers,circuitbreakerevents # Enable circuit breaker metrics
#  endpoint:
#    health:
#      show-details: always
#  security:
#    enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka/

server:
  port: 8083

jwt:
  secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    resilience4j.circuitbreaker: DEBUG