spring:
  application:
    name: order-service

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  kafka:
    consumer:
      group-id: order-service-id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      ObjectMapper.writeValueAsString in below JSON format
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
#        Any Source
        spring.json.trusted.packages: "*"
#        Below is because we are expecting the Kafka Listener to receive the input parameter as below Class:  com.gaurav.orderservice.dto.OrderConfirmation
        spring.json.value.default.type: com.gaurav.orderservice.dto.OrderConfirmation
    bootstrap-servers: localhost:9092

kafka:
  topic:
    name: order-producer

server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  service-url: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

jwt:
  secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=


logging:
  level:
    org.springframework.cloud.gateway: DEBUG


